name = "ReadableRegex"
uuid = "cbbcb084-453d-4c4c-b292-e315607ba6a4"
authors = ["Julius Krumbiegel"]
version = "0.3.3"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
